<a href="https://colab.research.google.com/github/ilmaaliyaf/learn-deep-learning/blob/main/deeplearning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preliminaries

## Data Manipulation

In [1]:
import tensorflow as tf

In [5]:
x = tf.range(12)
x
# x.shape
# tf.size(x)

TensorShape([12])

In [13]:
# tf.reshape(x,(3,4))
tf.reshape(x,(6,-1))

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]], dtype=int32)>

In [18]:
# tf.zeros((2,2,3))
tf.ones((3,2,4))

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [26]:
tf.random.normal(shape=(2,3))
tf.constant([[1,2,3,4],[2,4,5,6]])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 4, 5, 6]], dtype=int32)>